### ISSUE TITLE
How to use Classication head ?

### ISSUE THREAD

**Issue by boxbox2** [blaz-r/SuperSimpleNet#3]
Could you please tell me where the Classication head in the paper is in the code? How can I use it? thanks a lot

**Comment by blaz-r** [comment]
Hi, the classification head is located inside discriminator and consists of two parts `dec_head` conv block and `fc_score` fully connected layer: https://github.com/blaz-r/SuperSimpleNet/blob/60d1e742c836bdd5cd24388ffb2250059faa2ec4/model/supersimplenet.py#L201-L211

and is used in it's forward pass:
https://github.com/blaz-r/SuperSimpleNet/blob/60d1e742c836bdd5cd24388ffb2250059faa2ec4/model/supersimplenet.py#L228-L248
where the convolutional block first produces the intermediate result `dec_out` based on anomaly map `map_dec_cop` from seg. head and features `input`. This intermediate result and the anomaly map are both avg and max pooled, combined, then fed into fully connected last layer which produces anomaly score.

**Comment by boxbox2** [comment]
> Hi, the classification head is located inside discriminator and consists of two parts `dec_head` conv block and `fc_score` fully connected layer:
> 
> https://github.com/blaz-r/SuperSimpleNet/blob/60d1e742c836bdd5cd24388ffb2250059faa2ec4/model/supersimplenet.py#L201-L211
> 
> and is used in it's forward pass:
> 
> https://github.com/blaz-r/SuperSimpleNet/blob/60d1e742c836bdd5cd24388ffb2250059faa2ec4/model/supersimplenet.py#L228-L248
> 
> 
> where the convolutional block first produces the intermediate result `dec_out` based on anomaly map `map_dec_cop` from seg. head and features `input`. This intermediate result and the anomaly map are both avg and max pooled, combined, then fed into fully connected last layer which produces anomaly score.
> Segmentation-detection module is designed to perform joint localisation and detection. If you want to use the classification head by itself, you will have to modify both the `dec_head` and the `fc_score` to not take the map as an input. I would however recommend that you replace the segmentation part with the network of your choice if you want to modify the architecture.

Oh,Thanks for your quick reply!
